### PR TITLE
PR #11 Bump

### LINKED ISSUE #13: Module build failed: SyntaxError: Unexpected token m
This is what I'm getting:

```
ERROR in ./src/components/config.json
Module build failed: SyntaxError: Unexpected token m
    at Object.parse (native)
    at Object.module.exports (/Users/me/my-project/node_modules/json-loader/index.js:7:48)
 @ ./src/components/Main.js 28:13-37
```

The relevant JSON file I'm trying to load:

```json
{
  "redirectUri": "http://localhost:8000/webpack-dev-server/"
}
```

I'm requiring it via `var Config = require('./config.json');`. I had the same error when I did `require('json!./config.json')`.

I have this in my list of `loaders`:

```javascript
{
  test: /\.json$/,
  loader: 'json-loader!json-loader'
}
```

I got the same error when I moved the loader to the `preLoaders` section.

This is the version I'm using: `"json-loader": "^0.5.4"`.

### PR DESCRIPTION
**Pull request by MartinMuzatko**
Please merge #11.

Closes #13

### CODE REVIEW

**Comment by auser** [comment]
bump ^^

**Comment by cyberco** [comment]
bump

**Comment by Martskin** [comment]
:+1:

**Comment by sokra** [comment]
The issue is incorrect configuration (json-loader applied twice), and this PR is just a workaround.

**Comment by bora89** [comment]
@sokra But what I want to use `json-loader` and `file-loader` togeter? It causes the same error. I want not only to load json, but also to copy `.json` files to my pubic dir.
```JavaScript
{ test: /\.json$/, loader: 'json-loader' },
{ test: /\.json$/, loader: 'file?name=data/[path][name].[ext]' },
```
How to be?

**Pull request closed without merging**
