### PR TITLE
Do not try to parse again the string if it's already parsed

### LINKED ISSUE #10: Error when trying to require a JSON file
Webpack version: 0.12.2

I'm getting this error:
```
ERROR in dir/~/json-loader!dir/embedded/config.json
    Module build failed: SyntaxError: Unexpected token m
        at Object.parse (native)
        at Object.module.exports (dir/node_modules/json-loader/index.js:7:48)
     @ dir/embedded/includers/index.js 12:21-51
```

and in the `includers/index.js` I have this line:

`var embeddedConfig = require("json!../config.json");`

After checking, the problem is that the json-loader gets called two times, and the first one returns the expected outcome: `"module.exports = {....}"` but the second time it has `"module.exports = {....}"` as a source, so it tries to parse the string to JSON and then it fails because it's not a valid JSON.

Is anyone else getting the same error or did I do something wrong in the configuration?

### PR DESCRIPTION
**Pull request by xavimb**
Fixes #10

### CODE REVIEW

**Comment by cheshire137** [comment]
Why did this get closed? #13 and #10 are still problems.

**Comment by MartinMuzatko** [comment]
Please merge!

**Comment by jeffreyluo** [comment]
so we can use module.exports to solve this problem ?@MartinMuzatko

**Comment by MartinMuzatko** [comment]
AFAIK, the json-loader should just require JSON files.
If you need `module.exports` I'd recommend using the default `module.exports = {}` as `js` file.
Please let me know if I'm wrong @jeffreyluo

**Comment by jeffreyluo** [comment]
yeah, I know what you mean, I had meet this problem too. 
For the moment, using the module.exports may be the only way?  @MartinMuzatko

**Comment by MartinMuzatko** [comment]
A proper specification for what use cases the JSON-loader really is for would be great. AFAIK the point of the JSON Loader is to require JSON Files without needing to do a `module.exports`

**Comment by arahansen** [comment]
I'm still having issues with this bug. I'm not sure I understand why this PR isn't being merged. Can @xavimb or @sokra share a bit on the reasoning here?

Also, is there a workaround in the meantime?

**Comment by elliotchance** [comment]
I too came across this error. I managed to fix it with this patch (*fix* is the wrong word, *prove that the library is broken* is more appropriate).

I'm also left wondering why it wasn't merged in or at least explained?

**Comment by mikeerickson** [comment]
+1

**Comment by warrenseine** [comment]
I think it's not merged because it's a workaround, as explained by @MartinMuzatko. A fix should be applied either in the calling library (which parses JSON twice) or in the libraries using `.json` extension for `.js` files.

The thing is, libraries should just have a `.js` file that requires the JSON (see [`mime-db`](https://github.com/jshttp/mime-db/blob/master/index.js)). This way, you can just use a `raw-loader` and avoid these errors.

**Comment by bora89** [comment]
Guys, I want to use `json-loader` and `file-loader` togeter? It causes the same error. I want not only to load json, but also to copy `.json` files to my pubic dir.
```JavaScript
{ test: /\.json$/, loader: 'json-loader' },
{ test: /\.json$/, loader: 'file?name=data/[path][name].[ext]' },
```
How to be?

**Comment by elliotchance** [comment]
@bora89 you should open that as a new issue, otherwise you won't get any attention on a close issue.

**Pull request closed without merging**
